version: '3'

x-mongo-config:
  &env_mongo
  MONGODB_URI: mongodb://mongodb:27017/local-db?authSource=admin
  MONGODB_USERNAME: root
  MONGODB_PASSWORD: 8Jqi1hk4TRMltV4UGl5twmNvN
  MONGODB_REPLICASET: rs0
  MONGODB_REPLICA_SET_NAME: rs0
  MONGODB_REPLICA_SET_MODE: primary
  MONGODB_REPLICA_SET_KEY: replsetkey
  MONGODB_ROOT_PASSWORD: 8Jqi1hk4TRMltV4UGl5twmNvN
  MONGODB_ADVERTISED_HOSTNAME: mongodb
  MONGODB_MIN_POOL_SIZE: 1
  MONGODB_MAX_POOL_SIZE: 5


services:
  ui:
    image: node:18
    hostname: ui
    mem_limit: 4096MB
    command: yarn start ui --host=0.0.0.0
    working_dir: /usr/src/app
    volumes: [ .:/usr/src/app ]
    ports: [ '4200:4200' ]
    environment:
      PORT: 4200
      <<: [ *env_mongo ]

  # api:
  #   image: node:18
  #   hostname: api
  #   mem_limit: 4096MB
  #   command: yarn start api
  #   working_dir: /usr/src/app
  #   volumes: [ .:/usr/src/app ]
  #   ports: [ '3000:3000' ]
  #   environment:
  #     PORT: 3000
  #     <<: [ *env_mongo ]

  mongodb:
    image: bitnami/mongodb:4.2 # mongo:4.2.3-bionic
    hostname: mongodb
    ports: [ '27018:27017' ]
    environment:
      <<: *env_mongo
